version: '3'

services:
  django:
    build: .
    volumes:
      - .:/code
    environment:
      - DEBUG=True
    ports:
      - 8000:8000
      - 5678:5678
    command:
      python manage.py runserver 0.0.0.0:8000
